# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ca8f9b9640d0171ad86812004e23829a0b3e47161ec304f2acda9fab9dfc5d4571a9f576b5f81f1f3404c5587b452e919df22902e60540ed0cf7582e1d1c61f

test:
  secret_key_base: 2395308f9c0585b54c4178d5c4ac2205785f68d74798b34aabff5399bdfd057c34046c054f332ec2e8ae153f3f9ac11126154c49f43e94a9530088720c1cec3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
